---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/cert-manager.io/certificate_v1.json
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: "${SECRET_DOMAIN/./-}-production"
spec:
  dnsNames: ["${SECRET_DOMAIN}", "*.${SECRET_DOMAIN}"]
  duration: 160h
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  secretName: "${SECRET_DOMAIN/./-}-production-tls"
  usages:
    - digital signature
---
# yaml-language-server: $schema=https://schemas.tholinka.dev/cert-manager.io/certificate_v1.json
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: '${SECRET_DOMAIN/./-}-unifi'
spec:
  dnsNames:
    - 'unifi.${SECRET_DOMAIN}'
  duration: 160h
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  secretName: '${SECRET_DOMAIN/./-}-unifi'
  usages:
    - digital signature
  keystores:
    jks:
      create: true
      alias: unifi
      password: aircontrolenterprise
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/cert-manager.io/certificate_v1.json
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: "${SECRET_DOMAIN_2/./-}-production"
spec:
  dnsNames: ["${SECRET_DOMAIN_2}", "*.${SECRET_DOMAIN_2}"]
  duration: 160h
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  secretName: "${SECRET_DOMAIN_2/./-}-production-tls"
  usages:
    - digital signature
